Repository DIT112-V20/group-08, pull requests merged in 2020-04, with the labels that each got.

#17 Obstacle avoidance
  obstacle_avoidance_VL53L0X.ino
Labels: sprint1

#46 Car reads continuous bluetooth signal
  arduino/smartcar.ino
Labels: sprint2

#47 Updated: App backend directions and connections
  app/app/src/main/java/com/example/testcar/MainActivity.java
Labels: sprint2

#49 Added github link onclick effect
  app/app/src/main/java/com/example/testcar/MainActivity.java
Labels: sprint3

#61 Update to front end UI
  app/app/src/main/AndroidManifest.xml
  app/app/src/main/java/com/example/mcsc/MainActivity.java
  app/app/src/main/res/drawable-v24/GitHub-Mark-Light-120px-plus.png
  app/app/src/main/res/drawable-v24/GitHub-Mark-Light-32px.png
  app/app/src/main/res/drawable-v24/GitHub-Mark-Light-64px.png
  app/app/src/main/res/drawable-v24/backward.png
  app/app/src/main/res/drawable-v24/bluetooth.png
  app/app/src/main/res/drawable-v24/bottom-left.png
  app/app/src/main/res/drawable-v24/bottom-right.png
  app/app/src/main/res/drawable-v24/button_text.xml
  app/app/src/main/res/drawable-v24/forward.png
  app/app/src/main/res/drawable-v24/github.png
  app/app/src/main/res/drawable-v24/left.png
  app/app/src/main/res/drawable-v24/nav_backward.png
  app/app/src/main/res/drawable-v24/nav_forward.png
  app/app/src/main/res/drawable-v24/nav_left.png
  app/app/src/main/res/drawable-v24/nav_right.png
  app/app/src/main/res/drawable-v24/right.png
  app/app/src/main/res/drawable-v24/top-left.png
  app/app/src/main/res/drawable-v24/top-right.png
  app/app/src/main/res/drawable-v24/wifi.png
  app/app/src/main/res/drawable/bg_connectbtn.xml
  app/app/src/main/res/drawable/bg_controlbtn.xml
  app/app/src/main/res/drawable/bg_main.xml
  app/app/src/main/res/drawable/bg_switchbtn.xml
  app/app/src/main/res/drawable/main_background.xml
  app/app/src/main/res/font/nunito_semibold.xml
  app/app/src/main/res/layout/activity_main.xml
  app/app/src/main/res/layout/content_connect.xml
  app/app/src/main/res/layout/content_controls.xml
  app/app/src/main/res/layout/content_eeg.xml
  app/app/src/main/res/layout/content_header.xml
  app/app/src/main/res/layout/content_switch.xml
  app/app/src/main/res/values/dimens.xml
  app/app/src/main/res/values/preloaded_fonts.xml
  app/app/src/main/res/values/strings.xml
  app/app/src/main/res/values/styles.xml
Labels: sprint2

#68 Liv ui eeg
  app/app/src/main/java/com/example/myapplication/MainActivity.java
  app/app/src/main/res/drawable/bg_eegcontrol_start.xml
  app/app/src/main/res/drawable/bg_eegcontrol_stop.xml
  app/app/src/main/res/layout/content_controls.xml
  app/app/src/main/res/layout/content_eeg.xml
  app/app/src/main/res/values/strings.xml
  app/app/src/main/res/values/styles.xml
Labels: sprint2, sprint3

#72 Added Backward and goToUrl
  app/app/src/main/java/com/example/myapplication/MainActivity.java
Labels: sprint3

#79 Add feature turn clockwise and counterclockwise to smartcar
  arduino/smartcar/smartcar.ino
Labels: sprint3
