Repository DIT112-V20/group-08, pull requests merged in 2020-05, with the labels that each got.

#84 New header
  app/app/src/main/AndroidManifest.xml
  app/app/src/main/java/com/example/myapplication/MainActivity.java
  app/app/src/main/res/drawable-v24/bluetooth.png
  app/app/src/main/res/drawable-v24/github.png
  app/app/src/main/res/drawable-v24/icon_bluetooth_connected.xml
  app/app/src/main/res/drawable-v24/icon_bluetooth_disconnected.xml
  app/app/src/main/res/drawable-v24/icon_controls.xml
  app/app/src/main/res/drawable-v24/icon_github.png
  app/app/src/main/res/drawable-v24/icon_headset.xml
  app/app/src/main/res/drawable-v24/icon_wifi_connected.xml
  app/app/src/main/res/drawable-v24/icon_wifi_disconnected.xml
  app/app/src/main/res/drawable-v24/wifi.png
  app/app/src/main/res/drawable/bg_connectbtn.xml
  app/app/src/main/res/drawable/bg_main.xml
  app/app/src/main/res/drawable/bg_switchbtn.xml
  app/app/src/main/res/drawable/btn_github.xml
  app/app/src/main/res/drawable/car_control_button.xml
  app/app/src/main/res/drawable/main_background.xml
  app/app/src/main/res/font/nunito_bold.xml
  app/app/src/main/res/font/nunito_light.xml
  app/app/src/main/res/layout/activity_main.xml
  app/app/src/main/res/layout/content_connect.xml
  app/app/src/main/res/layout/content_eeg.xml
  app/app/src/main/res/layout/content_header.xml
  app/app/src/main/res/layout/content_joystick.xml
  app/app/src/main/res/layout/content_switch.xml
  app/app/src/main/res/values/colors.xml
  app/app/src/main/res/values/preloaded_fonts.xml
  app/app/src/main/res/values/strings.xml
  app/app/src/main/res/values/styles.xml
Labels: sprint3

#89 Eeg animation
  README.md
  app/app/src/main/java/com/example/myapplication/MainActivity.java
  app/app/src/main/res/drawable/circle.xml
  app/app/src/main/res/layout/content_eeg.xml
Labels: sprint4

#98 Car
  arduino/obstacle_avoidance_VL53L0X.ino
  arduino/smartcar/smartcar.ino
Labels: sprint3, sprint4

#99 Change output to car from string to int
  app/app/src/main/java/com/example/myapplication/MainActivity.java
Labels: sprint4

#101 Bug fixing
  arduino/smartcar/smartcar.ino
Labels: help wanted, sprint 5

#108 UI EEG display changed from "TextView" to descriptive default content.
  app/app/src/main/res/layout/content_eeg.xml
  app/app/src/main/res/values/strings.xml
  app/app/src/main/res/values/styles.xml
Labels: sprint 5

#113 Toasts added to click listeners for connection prompt
  app/app/src/main/java/com/example/myapplication/MainActivity.java
  app/app/src/main/java/com/example/myapplication/Toasty.java
  app/app/src/main/res/values/strings.xml
Labels: sprint 6

#116 Final (?) pulse animation for eeg reading display
  app/app/src/main/java/com/example/myapplication/MainActivity.java
  app/app/src/main/java/com/example/myapplication/PulseView.java
  app/app/src/main/res/layout/content_eeg.xml
  app/app/src/main/res/values/styles.xml
Labels: sprint 5, sprint 6

#112 Further bug fixes for the arduino code
  arduino/smartcar/smartcar.ino
Labels: High priority, sprint 5

#120 EEG dependent animation changes
  app/app/src/main/java/com/example/myapplication/MainActivity.java
  app/app/src/main/java/com/example/myapplication/PulseView.java
  app/app/src/main/res/drawable/bg_eegcontrol_start.xml
  app/app/src/main/res/drawable/bg_eegcontrol_stop.xml
  app/app/src/main/res/layout/content_eeg.xml
Labels: enhancement, sprint 6

#122 Revert "EEG dependent animation changes"
  app/app/src/main/java/com/example/myapplication/MainActivity.java
  app/app/src/main/java/com/example/myapplication/PulseView.java
  app/app/src/main/res/drawable/bg_eegcontrol_start.xml
  app/app/src/main/res/drawable/bg_eegcontrol_stop.xml
  app/app/src/main/res/layout/content_eeg.xml
Labels: sprint 6

#117 Joystick UI and method
  .DS_Store
  app/app/src/main/java/com/example/myapplication/JoyStick.java
  app/app/src/main/java/com/example/myapplication/MainActivity.java
  app/app/src/main/res/drawable/icon_round_arrow.png
  app/app/src/main/res/drawable/joystick_trackpad_background.xml
  app/app/src/main/res/drawable/joystick_trackpad_touch.xml
  app/app/src/main/res/layout/content_joystick.xml
  app/app/src/main/res/values/attrs.xml
  arduino/smartcar/smartcar.ino
Labels: sprint 5, sprint 6

#135 Calculation for animation change on eeg read
  app/app/src/main/java/com/example/myapplication/MainActivity.java
  app/app/src/main/java/com/example/myapplication/PulseView.java
  app/app/src/main/res/layout/content_eeg.xml
  app/app/src/main/res/layout/content_header.xml
Labels: sprint 6, sprint 7

#138 Tiny UI design update
  app/app/src/main/java/com/example/myapplication/MainActivity.java
  app/app/src/main/res/drawable/bg_eegcontrol_start.xml
  app/app/src/main/res/drawable/bg_eegcontrol_stop.xml
  app/app/src/main/res/values/styles.xml
Labels: sprint 7

#141 Toast update - simplified notifications
  app/app/src/main/java/com/example/myapplication/MainActivity.java
  app/app/src/main/java/com/example/myapplication/Toasty.java
Labels: enhancement, sprint 7

#145 The previous animation commit didn't work as intended. Revert to former.
  app/app/src/main/java/com/example/myapplication/PulseView.java
Labels: sprint 7

#143 Clean up
  app/app/src/main/java/com/example/myapplication/MainActivity.java
  app/app/src/main/res/drawable-v24/backward.png
  app/app/src/main/res/drawable-v24/forward.png
  app/app/src/main/res/drawable-v24/left.png
  app/app/src/main/res/drawable-v24/nav_backward.png
  app/app/src/main/res/drawable-v24/nav_forward.png
  app/app/src/main/res/drawable-v24/nav_left.png
  app/app/src/main/res/drawable-v24/nav_right.png
  app/app/src/main/res/drawable-v24/right.png
  app/app/src/main/res/drawable/bg_controlbtn.xml
  app/app/src/main/res/drawable/circle.xml
  app/app/src/main/res/drawable/icon_round_arrow.png
  app/app/src/main/res/layout/content_joystick.xml
  app/app/src/main/res/values/styles.xml
Labels: sprint 7

#139 Documentation - readme etc
  README.md
  readme-images/eeg-view.png
  readme-images/eeganimation.gif
  readme-images/joystick-view.png
  readme-images/neurodrive-system.png
Labels: sprint 7
